---
title: "Final Project"
author: "Shane Hauck"
date: '2022-03-21'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(fmsb)
library(scales)
library(plotly)
library(highcharter)
options(highcharter.theme = hc_theme_smpl(tooltip = list(valueDecimals = 2)))
library(knitr)
```

```{r}
epl_player_22 <- read_csv("data/epl_player_22.csv") %>% separate(player_positions, into = c("Pos1", "Pos2", "Pos3"), remove = FALSE)
epl_players <- epl_player_22 %>% select(c(4, 6:9, 12:17, 19, 23, 26, 28, 32, 110, 111, 114))

epl_comb <- left_join(epl_standard, epl_players)
epl_positions <- epl_comb %>% select(Name, Pos1, Pos2, Pos3)
```


```{r}
epl_standard <- read_csv("data/epl_standard.csv") %>% 
  select(-c(3, Matches)) %>%
  separate(Nation, into = c("irrel", "Nation"), sep = " ") %>%
  select(-c(irrel)) %>%
  select(-c(`Gls/90`, `Ast/90`, `G+A/90`, `G-PK/90`, `G+A-PK/90`, `xG/90`, `xA/90`, `xG+xA/90`, `npxG/90`, `npxG+xA/90`)) %>% 
  mutate(`G+A` = Gls + Ast)

epl_standard_90 <- read_csv("data/epl_standard_90.csv") %>% 
  select(-c(3, Matches)) %>%
  separate(Nation, into = c("irrel", "Nation"), sep = " ") %>%
  select(-c(irrel)) 
```

```{r}
epl_standard %>% 
  summarise(`25perc_90s` = quantile(`90s`, c(0.25)))
```


```{r}
epl_shooting <- read_csv("data/epl_shooting.csv", skip = 1) %>% 
  select(-c(3, Matches)) %>%
  separate(Nation, into = c("irrel", "Nation"), sep = " ") %>%
  select(-c(irrel)) %>%
  select(-c(`Sh/90`, `SoT/90`))

epl_shooting_90 <- read_csv("data/epl_shooting_90.csv", skip = 1) %>% 
  select(-c(3, Matches)) %>%
  separate(Nation, into = c("irrel", "Nation"), sep = " ") %>%
  select(-c(irrel)) %>%
  select(-c(`Sh/90`, `SoT/90`))

shooting_descr <- read_csv("data/shooting_descr.csv")
```

```{r}
epl_shooting_max <- epl_shooting %>% 
  drop_na() %>%
  filter(`90s` >= 4,
         Pos != "GK") %>% 
  summarise_if(is.numeric, max)
epl_shooting_min <- epl_shooting %>% 
  drop_na() %>%
  filter(`90s` >= 4,
         Pos != "GK") %>%
  summarise_if(is.numeric, min) 

epl_shoot_player <- epl_shooting %>% filter(Name == "Cristiano Ronaldo")

epl_shooting_max_min <- bind_rows(epl_shooting_max, epl_shooting_min)

epl_shoot_full <- bind_rows(epl_shooting_max_min, epl_shoot_player) %>%
  select(-c(Age, Squad, Pos, Nation, Name, Rk, Born, `90s`, FK, PKatt, PK))

epl_shoot_full_scaled <- epl_shoot_full %>% mutate(type = c("max", "min","player")) %>%
  pivot_longer(c(1:ncol(epl_shoot_full)), names_to = "variable", values_to = "value") %>%
  group_by(variable) %>%
  mutate(value.scaled = (value - min(value)) / (max(value) - min(value))) %>%
  filter(type == "player") %>%
  pivot_wider(names_from = variable, values_from = value.scaled) %>%
  mutate(`G-xG` = 1 - `G-xG`,
         `np:G-xG` = 1- `np:G-xG`) %>%
  rename(Goals = Gls,
         Shots = Sh,
         `Shots on Target` = SoT,
         `Shots on Target%` = `SoT%`,
         `Goals/Shot` = `G/Sh`,
         `Goals/Shot on Target` = `G/SoT`,
         Distance = Dist,
         `Non Penalty: xGoals/Shot` = `npxG/Sh`,
         `Non Penalty: Goals - xGoals` = `np:G-xG`,
         `Goals - xGoals` = `G-xG`,
         `Non Penalty xGoals` = npxG,
         `xGoals` = xG) %>%
  pivot_longer(c(1:ncol(epl_shoot_full) + 2), names_to = "variable", values_to = "value.scaled") %>%
  filter(!is.na(value.scaled)) %>%
  arrange(match(variable, c("Goals",
                            "Shots",
                            "Goals/Shot",
                            "Shots on Target",
                            "Shots on Target%",
                            "Goals/Shot on Target",
                            "Distance",
                            "Non Penalty: xGoals/Shot",
                            "Non Penalty: Goals - xGoals",
                            "Non Penalty xGoals",
                            "Goals - xGoals",
                            "xGoals"))) 


shooting_plot <- highchart() %>%
  hc_chart(polar = TRUE) %>%
  hc_add_theme(hc_theme_db()) %>%
  hc_xAxis(categories = epl_shoot_full_scaled$variable) %>%
  hc_yAxis(tickAmount = 5,
           max = 1,
           tickPixelInterval = 0.01,
           shared = TRUE) %>%
  hc_title(text = epl_shoot_player$Name,
           align = "center") %>%
  hc_subtitle(text = epl_shoot_player$Squad,
              align = "center") %>%
  hc_add_series(data = shooting_descr,
                mapping = hcaes(x = variable, y = 1),
                type = "scatter",
                tooltip = list(headerFormat = "", pointFormat = "{point.description}"),
                animation = FALSE,
                showInLegend = FALSE) %>%  
  hc_add_series(data = epl_shoot_full_scaled, 
                mapping = hcaes(x = variable, y = value.scaled), 
                type = "column",
                tooltip = list(headFormat = "{point.variable}", pointFormat = "{point.value}"),
                showInLegend = FALSE,
                pointWidth = 0.5,
                borderColor = "darkgrey",
                borderWidth = .2) 
```

```{r}
epl_shooting_rank <- epl_shooting %>%
  filter(`90s` >= 4,
         Pos != "GK") %>%
  drop_na() %>%
  mutate(across(-c(Age, Squad, Pos, Nation, Name, Rk, Born, `90s`, FK, PKatt, PK), min_rank, .names = "rank_{.col}")) %>%
  mutate(`rank_G-xG` = rank(-`G-xG`),
         `rank_np:G-xG` = rank(-`np:G-xG`))

epl_shooting_rank_max <- epl_shooting_rank %>%
  drop_na() %>%
  filter(`90s` >= 4,
         Pos != "GK") %>% 
  summarise_if(is.numeric, max)

epl_shooting_rank_min <- epl_shooting_rank %>%
  drop_na() %>%
  filter(`90s` >= 4,
         Pos != "GK") %>% 
  summarise_if(is.numeric, min)

epl_shooting_rank_player <- epl_shooting_rank %>% filter(Name == "Cristiano Ronaldo")

epl_shooting_rank_max_min <- bind_rows(epl_shooting_rank_max, epl_shooting_rank_min)

epl_shooting_rank_full <- bind_rows(epl_shooting_rank_max_min, epl_shooting_rank_player) %>%
  select(-c(Age, Squad, Pos, Nation, Name, Rk, Born, `90s`, FK, PKatt, PK))

epl_shooting_var_vals <- epl_shooting_rank_player %>% 
  select(-c(Age, Squad, Pos, Nation, Name, Rk, Born, `90s`, FK, PKatt, PK)) %>%
  pivot_longer(everything(), names_to = "variable", values_to = "value") %>%
  slice(c(1:12))

epl_shooting_var_ranks <- epl_shooting_rank_full %>% 
  select(-c(1:12)) %>%
  mutate(type = c("max", "min","player")) %>%
  pivot_longer(cols = c(1:12), names_to = "rankVar", values_to = "rankVal") %>%
  group_by(rankVar) %>%
  mutate(rank.scaled = (rankVal/ (max(rankVal)))) %>%
  filter(type == "player")
  
epl_shooting_rank_final <- bind_cols(epl_shooting_var_vals, epl_shooting_var_ranks) %>%
  pivot_wider(names_from = variable, values_from = value) %>%
  rename(Goals = Gls,
         Shots = Sh,
         `Shots on Target` = SoT,
         `Shots on Target%` = `SoT%`,
         `Goals/Shot` = `G/Sh`,
         `Goals/Shot on Target` = `G/SoT`,
         Distance = Dist,
         `Non Penalty: xGoals/Shot` = `npxG/Sh`,
         `Non Penalty: Goals - xGoals` = `np:G-xG`,
         `Goals - xGoals` = `G-xG`,
         `Non Penalty xGoals` = npxG,
         `xGoals` = xG) %>%
  pivot_longer(c(5:16), names_to = "variable", values_to = "value") %>%
  filter(!is.na(value)) %>%
  arrange(match(variable, c("Goals",
                            "Shots",
                            "Goals/Shot",
                            "Shots on Target",
                            "Shots on Target%",
                            "Goals/Shot on Target",
                            "Distance",
                            "Non Penalty: xGoals/Shot",
                            "Non Penalty: Goals - xGoals",
                            "Non Penalty xGoals",
                            "Goals - xGoals",
                            "xGoals"))) 

shooting_rank_plot <- highchart() %>%
  hc_chart(polar = TRUE) %>%
  hc_add_theme(hc_theme_db()) %>%
  hc_xAxis(categories = epl_shoot_full_scaled$variable) %>%
  hc_yAxis(tickAmount = 5,
           max = 1,
           tickPixelInterval = 0.01,
           shared = TRUE) %>%
  hc_title(text = epl_shooting_rank_player$Name,
           align = "center") %>%
  hc_subtitle(text = epl_shooting_rank_player$Squad,
              align = "center") %>%
  hc_add_series(data = shooting_descr,
                mapping = hcaes(x = variable, y = 1),
                type = "scatter",
                tooltip = list(headerFormat = "", pointFormat = "{point.description}"),
                animation = FALSE,
                showInLegend = FALSE) %>%  
  hc_add_series(data = epl_shooting_rank_final, 
                mapping = hcaes(x = variable, y = rank.scaled), 
                type = "column",
                tooltip = list(headFormat = "{point.variable}", pointFormat = "{point.value}"),
                showInLegend = FALSE,
                pointWidth = 0.5,
                borderColor = "darkgrey",
                borderWidth = .2) 
```

```{r}
epl_shoot_table <- epl_shoot_full_scaled %>% select(variable, value, value.scaled) %>%
  rename(Stat = variable,
         Value = value,
         `Scaled Value` = value.scaled)
kable(epl_shoot_table, digits = 3, title = "Shooting")
```


```{r}
epl_shooting_90_max <- epl_shooting_90 %>% 
  drop_na() %>%
  filter(`90s` >= 4) %>% 
  summarise_if(is.numeric, max )
epl_shooting_90_min <- epl_shooting_90 %>%  
  drop_na() %>%
  filter(`90s` >= 4) %>%
  summarise_if(is.numeric, min) 

epl_shoot_90_player <- epl_shooting_90 %>% filter(Name == "Cristiano Ronaldo")

epl_shooting_90_max_min <- bind_rows(epl_shooting_90_max, epl_shooting_90_min)

epl_shoot_90_full <- bind_rows(epl_shooting_90_max_min, epl_shoot_90_player) %>%
  select(-c(Age, Squad, Pos, Nation, Name, Rk, Born, `90s`, FK, PKatt, PK))

epl_shoot_90_full_scaled <- epl_shoot_90_full %>% mutate(type = c("max", "min","player")) %>%
  pivot_longer(c(1:ncol(epl_shoot_90_full)), names_to = "variable", values_to = "value") %>%
  group_by(variable) %>%
  mutate(value.scaled = (value - min(value)) / (max(value) - min(value))) %>%
  filter(type == "player") %>%
  pivot_wider(names_from = variable, values_from = value.scaled) %>%
  mutate(`G-xG` = 1 - `G-xG`,
         `np:G-xG` = 1- `np:G-xG`) %>%
  rename(Goals = Gls,
         Shots = Sh,
         `Shots on Target` = SoT,
         `Shots on Target%` = `SoT%`,
         `Goals/Shot` = `G/Sh`,
         `Goals/Shot on Target` = `G/SoT`,
         Distance = Dist,
         `Non Penalty: xGoals/Shot` = `npxG/Sh`,
         `Non Penalty: Goals - xGoals` = `np:G-xG`,
         `Goals - xGoals` = `G-xG`,
         `Non Penalty xGoals` = npxG,
         `xGoals` = xG) %>%
  pivot_longer(c(1:ncol(epl_shoot_full) + 2), names_to = "variable", values_to = "value.scaled") %>%
  filter(!is.na(value.scaled)) %>%
  arrange(match(variable, c("Goals",
                            "Shots",
                            "Goals/Shot",
                            "Shots on Target",
                            "Shots on Target%",
                            "Goals/Shot on Target",
                            "Distance",
                            "Non Penalty: xGoals/Shot",
                            "Non Penalty: Goals - xGoals",
                            "Non Penalty xGoals",
                            "Goals - xGoals",
                            "xGoals"))) 


shooting_90_plot <- highchart() %>%
  hc_chart(polar = TRUE, backgroundColor = "lightgrey") %>%
  hc_add_series(data = shooting_descr,
                mapping = hcaes(x = variable, y = 1),
                type = "point",
                color = "lightgrey",
                tooltip = list(headerFormat = "", pointFormat = "{point.description}"),
                animation = FALSE,
                showInLegend = FALSE) %>%   
  hc_add_series(data = epl_shoot_90_full_scaled, 
                mapping = hcaes(x = variable, y = value.scaled), 
                type = "column",
                color = rgb(0,255,100, maxColorValue = 255),
                tooltip = list(pointFormat = "{point.variable}: {point.value}"),
                showInLegend = FALSE,
                pointWidth = 0.5,
                borderColor = "darkgrey",
                borderWidth = .2) %>%
  hc_xAxis(categories = epl_shoot_full_scaled$variable) %>%
  hc_yAxis(tickAmount = 5,
           max = 1,
           tickPixelInterval = 0.01) %>%
  hc_title(text = epl_shoot_90_player$Name,
           align = "center") %>%
  hc_subtitle(text = epl_shoot_90_player$Squad,
              align = "center")
```

```{r}
epl_shoot_90_table <- epl_shoot_90_full_scaled %>% select(variable, value, value.scaled) %>%
  rename(Stat = variable,
         Value = value,
         `Scaled Value` = value.scaled)
kable(epl_shoot_90_table, digits = 3, title = "Shooting per 90 Minutes")
```


```{r}
epl_passing <- read_csv("data/epl_passing.csv") %>% 
  select(-c(3, Matches)) %>%
  separate(Nation, into = c("irrel", "Nation"), sep = " ") %>%
  select(-c(irrel))

epl_passing_90 <- read_csv("data/epl_passing_90.csv", skip = 1) %>% 
  select(-c(3, Matches)) %>%
  separate(Nation, into = c("irrel", "Nation"), sep = " ") %>%
  select(-c(irrel))
```

```{r}
passing_descr <- read_csv("data/passing_descr.csv")
```


```{r}
epl_passtype <- read_csv("data/epl_passtypes.csv", skip = 1) %>% 
  select(-c(3, Matches)) %>%
  separate(Nation, into = c("irrel", "Nation"), sep = " ") %>%
  select(-c(irrel))

epl_passtype_90 <- read_csv("data/epl_passtypes_90.csv", skip = 1) %>% 
  select(-c(3, Matches)) %>%
  separate(Nation, into = c("irrel", "Nation"), sep = " ") %>%
  select(-c(irrel))
```

```{r}
epl_goalandshotcreation <- read_csv("data/epl_goalandshotcreation.csv", skip = 1) %>% 
  select(-c(3, Matches)) %>%
  separate(Nation, into = c("irrel", "Nation"), sep = " ") %>%
  select(-c(irrel))

epl_goalandshotcreation_90 <- read_csv("data/epl_goalandshotcreation_90.csv", skip = 1) %>% 
  select(-c(3, Matches)) %>%
  separate(Nation, into = c("irrel", "Nation"), sep = " ") %>%
  select(-c(irrel))
```
 
```{r}
epl_passing_fill <- left_join(epl_passing, epl_passtype)
epl_passing_comb <- left_join(epl_passing_fill, epl_goalandshotcreation) %>%
  rename(`1/3` = `3-Jan`) %>%
  mutate(SCA_passes = SCA_PassLive + SCA_PassDead,
         GCA_passes = GCA_PassLive + GCA_PassDead)

epl_passing_main <- epl_passing_comb %>% 
  select(c(1:11, 14,16,17,19,20,22:24, 26:28,30,35:38, 72,73))

epl_passing_main_max <- epl_passing_main %>% 
  drop_na() %>%
  filter(`90s` >= 4,
         Pos != "GK") %>% 
  summarise_if(is.numeric, max)
epl_passing_main_min <- epl_passing_main %>% 
  drop_na() %>%
  filter(`90s` >= 4,
         Pos != "GK") %>%
  summarise_if(is.numeric, min)

epl_pass_player <- epl_passing_main %>% filter(Name == "Joao Cancelo")

epl_passing_main_max_min <- bind_rows(epl_passing_main_max, epl_passing_main_min)

epl_pass_full <-bind_rows(epl_passing_main_max_min, epl_pass_player) %>%
  select(-c(Age, Squad, Pos, Nation, Name, Rk, Born, `90s`))

epl_pass_full_scaled <- epl_pass_full %>% mutate(type = c("max", "min","player")) %>%
  pivot_longer(c(1:ncol(epl_pass_full)), names_to = "variable", values_to = "value") %>%
  group_by(variable) %>%
  mutate(value.scaled = (value - min(value)) / (max(value) - min(value))) %>%
  filter(type == "player") %>%
  pivot_wider(names_from = variable, values_from = value.scaled) %>%
  rename(Completions = `Cmp Total`,
         Attempts = `Att Total`,
         `Completion %` = `Cmp% Total`,
         `Short Completions` = `Cmp Short`,
         `Short Completion %` = `Cmp% Short`,
         `Medium Completions` = `Cmp Medium`, 
         `Medium Completion %` = `Cmp% Medium`,
         `Long Completions` = `Cmp Long`,
         `Long Completion %` = `Cmp% Long`,
         `Progressive Completions` = Prog,
         Switches = Sw,
         `Pressure` = Press,
         `Through Balls` = TB,
         `Completions into Final 3rd` = `1/3`,
         `Completions into Penalty Area` = PPA,
         Crosses = Crs,
         `Key Passes` = KP,
         `Shot Creating Passes` = SCA_passes,
         `Goal Creating Passes` = GCA_passes,
         xAssists = xA,
         Assists = Ast) %>%
  pivot_longer(c(3:23), names_to = "variable", values_to = "value.scaled") %>%
  filter(!is.na(value.scaled)) %>%
  arrange(match(variable, c("Completions", 
                            "Attempts",
                            "Completion %",
                            "Short Completions",
                            "Short Completion %",
                            "Medium Completions",
                            "Medium Completion %",
                            "Long Completions",
                            "Long Completion %",
                            "Progressive Completions",
                            "Switches",
                            "Pressure",
                            "Through Balls",
                            "Completions into Final 3rd",
                            "Completions into Penalty Area",
                            "Crosses",
                            "Key Passes",
                            "Shot Creating Passes",
                            "Goal Creating Passes",
                            "xAssists",
                            "Assists")))
  

passing_plot <- highchart() %>%
  hc_chart(polar = TRUE, backgroundColor = "lightgrey") %>%
  hc_add_series(data = passing_descr,
                mapping = hcaes(x = variable, y = 1),
                type = "point",
                tooltip = list(headerFormat = "",pointFormat = "{point.description}"),
                color = "lightgrey",
                animation = FALSE,
                showInLegend = FALSE) %>%  
  hc_add_series(data = epl_pass_full_scaled, 
                mapping = hcaes(x = variable, y = value.scaled), 
                type = "column",
                color = rgb(0,255,100, maxColorValue = 255),
                tooltip = list(pointFormat = "{point.variable}: {point.value}"),
                showInLegend = FALSE,
                pointWidth = 0.25,
                borderColor = "darkgrey",
                borderWidth = .2) %>%
  hc_xAxis(categories = epl_pass_full_scaled$variable) %>%
  hc_yAxis(visible = FALSE,
           max = 1,
           tickPixelInterval = 0.01) %>%
  hc_title(text = epl_pass_player$Name,
           align = "center") %>%
  hc_subtitle(text = epl_pass_player$Squad,
              align = "center")
```

```{r}
epl_pass_table <- epl_pass_full_scaled %>% select(variable, value, value.scaled) %>%
  rename(Stat = variable,
         Value = value,
         `Scaled Value` = value.scaled)
kable(epl_pass_table, digits = 3, title = "Passing")
```


```{r}
epl_passing_90_fill <- left_join(epl_passing_90, epl_passtype_90)
epl_passing_90_comb <- left_join(epl_passing_90_fill, epl_goalandshotcreation_90) %>%
  rename(`1/3` = `3-Jan`) %>%
  mutate(SCA_passes = SCA_PassLive + SCA_PassDead,
         GCA_passes = GCA_PassLive + GCA_PassDead)

epl_passing_90_main <- epl_passing_90_comb %>% 
  select(c(1:11, 14,16,17,19,20, 22:24, 26:28,30,35:38, 72,73))

epl_passing_90_main_max <- epl_passing_90_main %>% 
  drop_na() %>%
  filter(`90s` >= 4,
         Pos != "GK") %>% 
  summarise_if(is.numeric, max)
epl_passing_90_main_min <- epl_passing_90_main %>% 
  drop_na() %>%
  filter(`90s` >= 4,
         Pos != "GK") %>%
  summarise_if(is.numeric, min)

epl_pass_90_player <- epl_passing_90_main %>% filter(Name == "Alex Telles")

epl_passing_90_main_max_min <- bind_rows(epl_passing_90_main_max, epl_passing_90_main_min)

epl_pass_90_full <-bind_rows(epl_passing_90_main_max_min, epl_pass_90_player) %>%
  select(-c(Age, Squad, Pos, Nation, Name, Rk, Born, `90s`))

epl_pass_90_full_scaled <- epl_pass_90_full %>% mutate(type = c("max", "min","player")) %>%
  pivot_longer(c(1:ncol(epl_pass_90_full)), names_to = "variable", values_to = "value") %>%
  group_by(variable) %>%
  mutate(value.scaled = (value - min(value)) / (max(value) - min(value))) %>%
  filter(type == "player") %>%
  pivot_wider(names_from = variable, values_from = value.scaled) %>%
  rename(Completions = `Cmp Total`,
         Attempts = `Att Total`,
         `Completion %` = `Cmp% Total`,
         `Short Completions` = `Cmp Short`,
         `Short Completion %` = `Cmp% Short`,
         `Medium Completions` = `Cmp Medium`, 
         `Medium Completion %` = `Cmp% Medium`,
         `Long Completions` = `Cmp Long`,
         `Long Completion %` = `Cmp% Long`,
         `Progressive Completions` = Prog,
         Switches = Sw,
         `Pressure` = Press,
         `Through Balls` = TB,
         `Completions into Final 3rd` = `1/3`,
         `Completions into Penalty Area` = PPA,
         Crosses = Crs,
         `Key Passes` = KP,
         `Shot Creating Passes` = SCA_passes,
         `Goal Creating Passes` = GCA_passes,
         xAssists = xA,
         Assists = Ast) %>%
  pivot_longer(c(3:23), names_to = "variable", values_to = "value.scaled") %>%
  filter(!is.na(value.scaled)) %>%
  arrange(match(variable, c("Completions", 
                            "Attempts",
                            "Completion %",
                            "Short Completions",
                            "Short Completion %",
                            "Medium Completions",
                            "Medium Completion %",
                            "Long Completions",
                            "Long Completion %",
                            "Progressive Completions",
                            "Switches",
                            "Pressure",
                            "Through Balls",
                            "Completions into Final 3rd",
                            "Completions into Penalty Area",
                            "Crosses",
                            "Key Passes",
                            "Shot Creating Passes",
                            "Goal Creating Passes",
                            "xAssists",
                            "Assists")))
  

passing_90_plot <- highchart() %>%
  hc_chart(polar = TRUE, backgroundColor = "lightgrey") %>%
   hc_add_series(data = epl_pass_90_full_scaled,
                mapping = hcaes(x = variable, y = 1),
                type = "point",
                tooltip = list(pointFormat = "{point.variable}"),
                color = "lightgrey",
                animation = FALSE,
                showInLegend = FALSE) %>%  
  hc_add_series(data = epl_pass_90_full_scaled, 
                mapping = hcaes(x = variable, y = value.scaled), 
                type = "column",
                color = rgb(0,255,100, maxColorValue = 255),
                tooltip = list(pointFormat = "{point.variable}: {point.value}"),
                showInLegend = FALSE,
                pointWidth = 0.25,
                borderColor = "darkgrey",
                borderWidth = .2) %>%
  hc_xAxis(categories = epl_pass_full_scaled$variable) %>%
  hc_yAxis(visible = FALSE,
           max = 1,
           tickPixelInterval = 0.01) %>%
  hc_title(text = epl_pass_90_player$Name,
           align = "center") %>%
  hc_subtitle(text = epl_pass_90_player$Squad,
              align = "center")
```

```{r}
epl_pass_90_table <- epl_pass_90_full_scaled %>% select(variable, value, value.scaled) %>%
  rename(Stat = variable,
         Value = value,
         `Scaled Value` = value.scaled)
kable(epl_pass_90_table, digits = 3, title = "Passing per 90 Minutes")
```

```{r}
epl_defensiveactions <- read_csv("data/epl_defensiveactions.csv", skip = 1) %>% 
  select(-c(3, Matches)) %>%
  separate(Nation, into = c("irrel", "Nation"), sep = " ") %>%
  select(-c(irrel))

epl_defensiveactions_90 <- read_csv("data/epl_defensiveactions_90.csv", skip = 1) %>% 
  select(-c(3, Matches)) %>%
  separate(Nation, into = c("irrel", "Nation"), sep = " ") %>%
  select(-c(irrel))
``` 

```{r}
epl_def_main <- epl_defensiveactions %>% 
  mutate(`TklsW%` = TklsW / Tkls * 100,
         `TklsW%` = as.numeric(format(round(`TklsW%`, 2)))) %>%
  select(c(1:14, 16, 18:23, 25, 27, 28, 30, 32))
  

epl_def_main_max <- epl_def_main %>% 
  drop_na() %>%
  filter(`90s` >= 4,
         Pos != "GK") %>% 
  summarise_if(is.numeric, max)
epl_def_main_min <- epl_def_main %>% 
  drop_na() %>%
  filter(`90s` >= 4,
         Pos != "GK") %>%
  summarise_if(is.numeric, min)

epl_def_player <- epl_def_main %>% filter(Name == "Aaron Wan-Bissaka")

epl_def_main_max_min <- bind_rows(epl_def_main_max, epl_def_main_min)

epl_def_full <-bind_rows(epl_def_main_max_min, epl_def_player) %>%
  select(-c(Age, Squad, Pos, Nation, Name, Rk, Born, `90s`)) 

epl_def_full_scaled <- epl_def_full %>% mutate(type = c("max", "min","player")) %>%
  pivot_longer(c(1:ncol(epl_def_full)), names_to = "variable", values_to = "value") %>%
  group_by(variable) %>%
  mutate(value.scaled = (value - min(value)) / (max(value) - min(value))) %>%
  filter(type == "player") %>%
  pivot_wider(names_from = variable, values_from = value.scaled) %>%
  rename(Tackles = Tkls,
         `Tackles Won` = TklsW,
         `% of Tackles Won` = `TklsW%`,
         `Tackles vs Dribbles` = `Tkls vs Drib`,
         `% of Dribbles Tackled` = `Tkl% vs Drib`,
         `Tackles in Attacking 3rd` = `Tkls Att 3rd`,
         `Tackles in Middle 3rd` = `Tkls Mid 3rd`,
         `Tackles in Defensive 3rd` = `TKls Def 3rd`,
         `Pressures` = Press,
         `Succesful Pressures` = `Succ Press`,
         `Succesful Pressures %` = `Press%`,
         `Pressures in Attacking 3rd` = `Press Att 3rd`,
         `Pressures in Middle 3rd` = `Press Mid 3rd`,
         `Pressures in Defensive 3rd` = `Press Def 3rd`,
         `Clearances` = Clr,
         `Blocked Shots` = `Blocked Sh`,
         `Blocked Passes` = `Blocked Pass`,
         Interceptions = Int) %>%
  pivot_longer(c(3:20), names_to = "variable", values_to = "value.scaled") %>%
  filter(!is.na(value.scaled)) %>%
  arrange(match(variable, c("Tackles",
                            "Tackles Won",
                            "% of Tackles Won",
                            "Tackles vs Dribbles",
                            "% of Dribbles Tackled",
                            "Tackles in Attacking 3rd",
                            "Tackles in Middle 3rd",
                            "Tackles in Defensive 3rd",
                            "Pressures",
                            "Succesful Pressures",
                            "Succesful Pressures %",
                            "Pressures in Attacking 3rd",
                            "Pressures in Middle 3rd",
                            "Pressures in Defensive 3rd",
                            "Clearances",
                            "Blocked Shots",
                            "Blocked Passes",
                            "Interceptions"))) 

 

def_plot <- highchart() %>%
  hc_chart(polar = TRUE, backgroundColor = "lightgrey", grouping = FALSE) %>%
  hc_add_series(data = epl_def_90_full_scaled,
                mapping = hcaes(x = variable, y = 1),
                type = "point",
                tooltip = list(pointFormat = "{point.variable}"),
                color = "lightgrey",
                animation = FALSE) %>%
  hc_add_series(data = epl_def_full_scaled, 
                mapping = hcaes(x = variable, y = value.scaled), 
                type = "column",
                color = rgb(0,255,100, maxColorValue = 255),
                tooltip = list(pointFormat = "{point.variable}: {point.value}"),
                showInLegend = FALSE,
                pointWidth = .25,
                borderColor = "darkgrey",
                borderWidth = .2) %>%
  hc_xAxis(categories = epl_def_full_scaled$variable) %>%
  hc_yAxis(visible = FALSE,
           max = 1,
           tickPixelInterval = 0.01) %>%
  hc_title(text = epl_def_player$Name,
           align = "center") %>%
  hc_subtitle(text = epl_def_player$Squad,
              align = "center") 
```

```{r}
epl_def_table <- epl_def_full_scaled %>% select(variable, value, value.scaled) %>%
  rename(Stat = variable,
         Value = value,
         `Scaled Value` = value.scaled)
kable(epl_def_table, digits = 3, title = "Defending")
```


```{r}
epl_def_90_main <- epl_defensiveactions_90 %>% 
  mutate(`TklsW%` = TklsW / Tkls * 100,
         `TklsW%` = as.numeric(format(round(`TklsW%`, 2)))) %>%
  select(c(1:14, 16, 18:23, 25, 27, 28, 30, 32))
  

epl_def_90_main_max <- epl_def_90_main %>% 
  drop_na() %>%
  filter(`90s` >= 4.01,
         Pos != "GK") %>% 
  summarise_if(is.numeric, max)
epl_def_90_main_min <- epl_def_90_main %>% 
  drop_na() %>%
  filter(`90s` >= 4,
         Pos != "GK") %>%
  summarise_if(is.numeric, min)

epl_def_90_player <- epl_def_90_main %>% filter(Name == "Declan Rice")

epl_def_90_main_max_min <- bind_rows(epl_def_90_main_max, epl_def_90_main_min)

epl_def_90_full <-bind_rows(epl_def_90_main_max_min, epl_def_90_player) %>%
  select(-c(Age, Squad, Pos, Nation, Name, Rk, Born, `90s`)) 

epl_def_90_full_scaled <- epl_def_90_full %>% mutate(type = c("max", "min","player")) %>%
  pivot_longer(c(1:ncol(epl_def_90_full)), names_to = "variable", values_to = "value") %>%
  group_by(variable) %>%
  mutate(value.scaled = (value - min(value)) / (max(value) - min(value))) %>%
  filter(type == "player") %>%
  pivot_wider(names_from = variable, values_from = value.scaled) %>%
  rename(Tackles = Tkls,
         `Tackles Won` = TklsW,
         `% of Tackles Won` = `TklsW%`,
         `Tackles vs Dribbles` = `Tkls vs Drib`,
         `% of Dribbles Tackled` = `Tkl% vs Drib`,
         `Tackles in Attacking 3rd` = `Tkls Att 3rd`,
         `Tackles in Middle 3rd` = `Tkls Mid 3rd`,
         `Tackles in Defensive 3rd` = `TKls Def 3rd`,
         `Pressures` = Press,
         `Succesful Pressures` = `Succ Press`,
         `Succesful Pressures %` = `Press%`,
         `Pressures in Attacking 3rd` = `Press Att 3rd`,
         `Pressures in Middle 3rd` = `Press Mid 3rd`,
         `Pressures in Defensive 3rd` = `Press Def 3rd`,
         `Clearances` = Clr,
         `Blocked Shots` = `Blocked Sh`,
         `Blocked Passes` = `Blocked Pass`,
         Interceptions = Int) %>%
  pivot_longer(c(3:20), names_to = "variable", values_to = "value.scaled") %>%
  filter(!is.na(value.scaled)) %>%
  arrange(match(variable, c("Tackles",
                            "Tackles Won",
                            "% of Tackles Won",
                            "Tackles vs Dribbles",
                            "% of Dribbles Tackled",
                            "Tackles in Attacking 3rd",
                            "Tackles in Middle 3rd",
                            "Tackles in Defensive 3rd",
                            "Pressures",
                            "Succesful Pressures",
                            "Succesful Pressures %",
                            "Pressures in Attacking 3rd",
                            "Pressures in Middle 3rd",
                            "Pressures in Defensive 3rd",
                            "Clearances",
                            "Blocked Shots",
                            "Blocked Passes",
                            "Interceptions"))) 

 
  

def_90_plot <- highchart() %>%
  hc_chart(polar = TRUE, backgroundColor = "lightgrey") %>%
    hc_add_series(data = epl_def_90_full_scaled,
                mapping = hcaes(x = variable, y = 1),
                type = "point",
                tooltip = list(pointFormat = "{point.variable}"),
                color = "lightgrey",
                animation = FALSE,
                showInLegend = FALSE) %>%  
  hc_add_series(data = epl_def_90_full_scaled, 
                mapping = hcaes(x = variable, y = value.scaled), 
                type = "column",
                color = rgb(0,255,100, maxColorValue = 255),
                tooltip = list(pointFormat = "{point.variable}: {point.value}"),
                showInLegend = FALSE,
                pointWidth = 0.25,
                borderColor = "darkgrey",
                borderWidth = .2) %>%
  hc_xAxis(categories = epl_def_full_scaled$variable) %>%
  hc_yAxis(visible = FALSE,
           max = 1,
           tickPixelInterval = 0.01) %>%
  hc_title(text = epl_def_90_player$Name,
           align = "center") %>%
  hc_subtitle(text = epl_def_90_player$Squad,
              align = "center")
```

```{r}
epl_def_90_table <- epl_def_full_scaled %>% select(variable, value, value.scaled) %>%
  rename(Stat = variable,
         Value = value,
         `Scaled Value` = value.scaled)
kable(epl_def_90_table, digits = 3, title = "Defending per 90 Minutes")
```
 
 
```{r}
epl_possesion <- read_csv("data/epl_possesion.csv", skip = 1) %>%
  select(-c(3, Matches)) %>%
  separate(Nation, into = c("irrel", "Nation"), sep = " ") %>%
  select(-c(irrel))

epl_possesion_90 <- read_csv("data/epl_possesion_90.csv", skip = 1) %>%
  select(-c(3, Matches)) %>%
  separate(Nation, into = c("irrel", "Nation"), sep = " ") %>%
  select(-c(irrel))
```

```{r}
epl_miscellaneous <- read_csv("data/epl_miscellaneous.csv", skip = 1) %>% 
  select(-c(3, Matches)) %>%
  separate(Nation, into = c("irrel", "Nation"), sep = " ") %>%
  select(-c(irrel))

epl_miscellaneous_90 <- read_csv("data/epl_miscellaneous_90.csv", skip = 1) %>% 
  select(-c(3, Matches)) %>%
  separate(Nation, into = c("irrel", "Nation"), sep = " ") %>%
  select(-c(irrel))
```

```{r}
poss_extra <- epl_miscellaneous %>% select(c(Recov, `AD Won`, `AD Won%`))
poss_extra2 <- epl_passing %>% select(c(9:13))
epl_poss_comb <- bind_cols(epl_possesion, poss_extra, poss_extra2)

epl_poss_main <- epl_poss_comb %>% 
  select(c(1:14, 27, 29:40))

epl_poss_main_max <- epl_poss_main %>% 
  drop_na() %>%
  filter(`90s` >= 4,
         Pos != "GK") %>% 
  summarise_if(is.numeric, max)
epl_poss_main_min <- epl_poss_main %>% 
  drop_na() %>%
  filter(`90s` >= 4,
         Pos != "GK") %>%
  summarise_if(is.numeric, min)

epl_poss_player <- epl_poss_main %>% filter(Name == "Joao Cancelo")

epl_poss_main_max_min <- bind_rows(epl_poss_main_max, epl_poss_main_min)

epl_poss_full <-bind_rows(epl_poss_main_max_min, epl_poss_player) %>%
  select(-c(Age, Squad, Pos, Nation, Name, Rk, Born))

epl_poss_full_scaled <- epl_poss_full %>% mutate(type = c("max", "min","player")) %>%
  pivot_longer(c(1:ncol(epl_poss_full)), names_to = "variable", values_to = "value") %>%
  group_by(variable) %>%
  mutate(value.scaled = (value - min(value)) / (max(value) - min(value))) %>%
  filter(type == "player") %>%
  pivot_wider(names_from = variable, values_from = value.scaled) %>%
  mutate(Miscontrol = 1 - Miscontrol) %>%
  rename(`Touches in Attacking Penalty Area` = `Touches Att Pen`,
         `Touches in Attacking 3rd` = `Touches Att 3rd`,
         `Touches in Middle 3rd` = `Touches Mid 3rd`,
         `Touches in Defensive 3rd` = `Touches Def 3rd`,
         `Touches in Defensive Penalty Area` = `Touches Def Pen`,
         Receptions = Rec,
         Targets = Targ,
         `Reception %` = `Rec%`,
         `Progressive Receptions` = `Prog Rec`,
         `% of Aerial Duels Won` = `AD Won%`,
         `Aerial Duels Won` = `AD Won`,
         `Recoveries` = Recov,
         `Progressive Distance` = PrgDist,
         `Total Distance` = TotDist,
         `Completion %` = `Cmp% Total`,
         `Attempts` = `Att Total`,
         `Completions` = `Cmp Total`)%>%
  pivot_longer(c(1:ncol(epl_poss_full) + 2), names_to = "variable", values_to = "value.scaled") %>%
  filter(!is.na(value.scaled)) %>%
  arrange(match(variable, c("Touches",
                            "Touches in Attacking Penalty Area",
                            "Touches in Attacking 3rd",
                            "Touches in Middle 3rd",
                            "Touches in Defensive 3rd",
                            "Touches in Defensive Penalty Area",
                            "Receptions",
                            "Targets",
                            "Reception %",
                            "Progressive Receptions",
                            "% of Aerial Duels Won",
                            "Aerial Duels Won",
                            "Recoveries",
                            "Miscontrol",
                            "Progressive Distance",
                            "Total Distance",
                            "Completion %",
                            "Attempts",
                            "Completions"
                            )))
  
  

poss_plot <- highchart() %>%
  hc_chart(polar = TRUE, backgroundColor = "lightgrey") %>%
  hc_add_series(data = epl_poss_full_scaled,
                mapping = hcaes(x = variable, y = 1),
                type = "point",
                tooltip = list(pointFormat = "{point.variable}"),
                color = "lightgrey",
                animation = FALSE,
                showInLegend = FALSE) %>%  
  hc_add_series(data = epl_poss_full_scaled, 
                mapping = hcaes(x = variable, y = value.scaled), 
                type = "column",
                color = rgb(0,255,100, maxColorValue = 255),
                tooltip = list(pointFormat = "{point.variable}: {point.value}"),
                showInLegend = FALSE,
                pointWidth = 0.25,
                borderColor = "darkgrey",
                borderWidth = .2) %>%
  hc_xAxis(categories = epl_poss_full_scaled$variable) %>%
  hc_yAxis(visible = FALSE,
           max = 1,
           tickPixelInterval = 0.01) %>%
  hc_title(text = epl_poss_player$Name,
           align = "center") %>%
  hc_subtitle(text = epl_poss_player$Squad,
              align = "center")
```

```{r}
epl_poss_table <- epl_poss_full_scaled %>% select(variable, value, value.scaled) %>%
  rename(Stat = variable,
         Value = value,
         `Scaled Value` = value.scaled)
kable(epl_poss_table, digits = 3, title = "Possesion")
```


```{r}
poss_90_extra <- epl_miscellaneous_90 %>% select(c(Recov, `AD Won`, `AD Won%`))
poss_90_extra2 <- epl_passing_90 %>% select(c(9:13))
epl_poss_90_comb <- bind_cols(epl_possesion_90, poss_90_extra, poss_90_extra2)

epl_poss_90_main <- epl_poss_90_comb %>% 
  select(c(1:14, 27, 29:40))

epl_poss_90_main_max <- epl_poss_90_main %>% 
  drop_na() %>%
  filter(`90s` >= 4,
         Pos != "GK") %>% 
  summarise_if(is.numeric, max)
epl_poss_90_main_min <- epl_poss_90_main %>% 
  drop_na() %>%
  filter(`90s` >= 4,
         Pos != "GK") %>%
  summarise_if(is.numeric, min)

epl_poss_90_player <- epl_poss_90_main %>% filter(Name == "Trent Alexander-Arnold")

epl_poss_90_main_max_min <- bind_rows(epl_poss_90_main_max, epl_poss_90_main_min)

epl_poss_90_full <-bind_rows(epl_poss_90_main_max_min, epl_poss_90_player) %>%
  select(-c(Age, Squad, Pos, Nation, Name, Rk, Born, `90s`))

epl_poss_90_full_scaled <- epl_poss_90_full %>% mutate(type = c("max", "min","player")) %>%
  pivot_longer(c(1:ncol(epl_poss_90_full)), names_to = "variable", values_to = "value") %>%
  group_by(variable) %>%
  mutate(value.scaled = (value - min(value)) / (max(value) - min(value))) %>%
  filter(type == "player") %>%
  pivot_wider(names_from = variable, values_from = value.scaled) %>%
  mutate(Miscontrol = 1 - Miscontrol) %>%
  rename(`Touches in Attacking Penalty Area` = `Touches Att Pen`,
         `Touches in Attacking 3rd` = `Touches Att 3rd`,
         `Touches in Middle 3rd` = `Touches Mid 3rd`,
         `Touches in Defensive 3rd` = `Touches Def 3rd`,
         `Touches in Defensive Penalty Area` = `Touches Def Pen`,
         Receptions = Rec,
         Targets = Targ,
         `Reception %` = `Rec%`,
         `Progressive Receptions` = `Prog Rec`,
         `% of Aerial Duels Won` = `AD Won%`,
         `Aerial Duels Won` = `AD Won`,
         `Recoveries` = Recov,
         `Progressive Distance` = PrgDist,
         `Total Distance` = TotDist,
         `Completion %` = `Cmp% Total`,
         `Attempts` = `Att Total`,
         `Completions` = `Cmp Total`)%>%
  pivot_longer(c(1:ncol(epl_poss_90_full) + 2), names_to = "variable", values_to = "value.scaled") %>%
  filter(!is.na(value.scaled)) %>%
  arrange(match(variable, c("Touches",
                            "Touches in Attacking Penalty Area",
                            "Touches in Attacking 3rd",
                            "Touches in Middle 3rd",
                            "Touches in Defensive 3rd",
                            "Touches in Defensive Penalty Area",
                            "Receptions",
                            "Targets",
                            "Reception %",
                            "Progressive Receptions",
                            "% of Aerial Duels Won",
                            "Aerial Duels Won",
                            "Recoveries",
                            "Miscontrol",
                            "Progressive Distance",
                            "Total Distance",
                            "Completion %",
                            "Attempts",
                            "Completions"
                            )))
  
  

poss_90_plot <- highchart() %>%
  hc_chart(polar = TRUE, backgroundColor = "lightgrey") %>%
  hc_add_series(data = epl_poss_90_full_scaled,
                mapping = hcaes(x = variable, y = 1),
                type = "point",
                tooltip = list(pointFormat = "{point.variable}"),
                color = "lightgrey",
                animation = FALSE,
                showInLegend = FALSE) %>%  
  hc_add_series(data = epl_poss_90_full_scaled, 
                mapping = hcaes(x = variable, y = value.scaled), 
                type = "column",
                color = rgb(0,255,100, maxColorValue = 255),
                tooltip = list(pointFormat = "{point.variable}: {point.value}"),
                showInLegend = FALSE,
                pointWidth = 0.25,
                borderColor = "darkgrey",
                borderWidth = .2) %>%
  hc_xAxis(categories = epl_poss_90_full_scaled$variable) %>%
  hc_yAxis(visible = FALSE,
           max = 1,
           tickPixelInterval = 0.01) %>%
  hc_title(text = epl_poss_90_player$Name,
           align = "center") %>%
  hc_subtitle(text = epl_poss_90_player$Squad,
              align = "center")

```

```{r}
epl_poss_90_table <- epl_poss_90_full_scaled %>% select(variable, value, value.scaled) %>%
  rename(Stat = variable,
         Value = value,
         `Scaled Value` = value.scaled)
kable(epl_poss_90_table, digits = 3, title = "Possesion per 90 Minutes")
```


```{r}
drib_extra <- epl_miscellaneous %>% select(c(Fld))
drib_extra2 <- epl_goalandshotcreation %>% select(c(SCA_Drib))
epl_drib_comb <- bind_cols(epl_possesion, drib_extra, drib_extra2)

epl_drib_main <- epl_drib_comb %>% 
  select(c(1:8, 16:28, 33:34))

epl_drib_main_max <- epl_drib_main %>% 
  drop_na() %>%
  filter(`90s` >= 4,
         Pos != "GK") %>% 
  summarise_if(is.numeric, max)
epl_drib_main_min <- epl_drib_main %>% 
  drop_na() %>%
  filter(`90s` >= 4,
         Pos != "GK") %>%
  summarise_if(is.numeric, min)

epl_drib_player <- epl_drib_main %>% filter(Name == "Joao Cancelo")

epl_drib_main_max_min <- bind_rows(epl_drib_main_max, epl_drib_main_min)

epl_drib_full <-bind_rows(epl_drib_main_max_min, epl_drib_player) %>%
  select(-c(Age, Squad, Pos, Nation, Name, Rk, Born, `90s`))

epl_drib_full_scaled <- epl_drib_full %>% mutate(type = c("max", "min","player")) %>%
  pivot_longer(c(1:ncol(epl_drib_full)), names_to = "variable", values_to = "value") %>%
  group_by(variable) %>%
  mutate(value.scaled = (value - min(value)) / (max(value) - min(value))) %>%
  filter(type == "player") %>%
  pivot_wider(names_from = variable, values_from = value.scaled) %>%
  mutate(Miscontrol = 1 - Miscontrol,
         Dispossessed = 1- Dispossessed) %>%
  pivot_longer(c(1:ncol(epl_drib_full) + 2), names_to = "variable", values_to = "value.scaled") %>%
  filter(!is.na(value.scaled)) %>%
  arrange(match(variable, c("Succ Drib",
                            "Att Drib",
                            "Succ% Drib",
                            "Drib Past",
                            "SCA_Drib",
                            "Fld",
                            "Megs",
                            "Dispossessed",
                            "Miscontrol",
                            "Carries into PA",
                            "Carries into Att 3rd",
                            "TotDist Carried",
                            "PrgDist Carried",
                            "Prog Carries",
                            "Carries"
                            )))
  

drib_plot <- highchart() %>%
  hc_chart(polar = TRUE, backgroundColor = "lightgrey") %>%
  hc_add_series(data = epl_drib_full_scaled,
                mapping = hcaes(x = variable, y = 1),
                type = "point",
                tooltip = list(pointFormat = "{point.variable}"),
                color = "lightgrey",
                animation = FALSE,
                showInLegend = FALSE) %>%  
  hc_add_series(data = epl_drib_full_scaled, 
                mapping = hcaes(x = variable, y = value.scaled), 
                type = "column",
                color = rgb(0,255,100, maxColorValue = 255),
                tooltip = list(pointFormat = "{point.variable}: {point.value}"),
                showInLegend = FALSE,
                pointWidth = 0.25,
                borderColor = "darkgrey",
                borderWidth = .2) %>%
  hc_xAxis(categories = epl_drib_full_scaled$variable) %>%
  hc_yAxis(visible = FALSE,
           max = 1,
           tickPixelInterval = 0.01) %>%
  hc_title(text = epl_drib_player$Name,
           align = "center") %>%
  hc_subtitle(text = epl_drib_player$Squad,
              align = "center")
```
 
```{r}
epl_drib_table <- epl_drib_full_scaled %>% select(variable, value, value.scaled) %>%
  rename(Stat = variable,
         Value = value,
         `Scaled Value` = value.scaled)
kable(epl_drib_table, digits = 3, title = "Dribbling")
```


```{r}
drib_90_extra <- epl_miscellaneous_90 %>% select(c(Fld))
drib_90_extra2 <- epl_goalandshotcreation_90 %>% select(c(SCA_Drib))
epl_drib_90_comb <- bind_cols(epl_possesion_90, drib_90_extra, drib_90_extra2)

epl_drib_90_main <- epl_drib_90_comb %>% 
  select(c(1:8, 16:28, 33:34))

epl_drib_90_main_max <- epl_drib_90_main %>% 
  drop_na() %>%
  filter(`90s` >= 4,
         Pos != "GK") %>% 
  summarise_if(is.numeric, max)
epl_drib_90_main_min <- epl_drib_90_main %>% 
  drop_na() %>%
  filter(`90s` >= 4,
         Pos != "GK") %>%
  summarise_if(is.numeric, min)

epl_drib_90_player <- epl_drib_90_main %>% filter(Name == "Joao Cancelo")

epl_drib_90_main_max_min <- bind_rows(epl_drib_90_main_max, epl_drib_90_main_min)

epl_drib_90_full <-bind_rows(epl_drib_90_main_max_min, epl_drib_90_player) %>%
  select(-c(Age, Squad, Pos, Nation, Name, Rk, Born, `90s`))

epl_drib_90_full_scaled <- epl_drib_90_full %>% mutate(type = c("max", "min","player")) %>%
  pivot_longer(c(1:ncol(epl_drib_90_full)), names_to = "variable", values_to = "value") %>%
  group_by(variable) %>%
  mutate(value.scaled = (value - min(value)) / (max(value) - min(value))) %>%
  filter(type == "player") %>%
  pivot_wider(names_from = variable, values_from = value.scaled) %>%
  mutate(Miscontrol = 1 - Miscontrol,
         Dispossessed = 1- Dispossessed) %>%
  pivot_longer(c(1:ncol(epl_drib_full) + 2), names_to = "variable", values_to = "value.scaled") %>%
  filter(!is.na(value.scaled)) %>%
  arrange(match(variable, c("Succ Drib",
                            "Att Drib",
                            "Succ% Drib",
                            "Drib Past",
                            "SCA_Drib",
                            "Fld",
                            "Megs",
                            "Dispossessed",
                            "Miscontrol",
                            "Carries into PA",
                            "Carries into Att 3rd",
                            "TotDist Carried",
                            "PrgDist Carried",
                            "Prog Carries",
                            "Carries"
                            )))
  
  

drib_90_plot <- highchart() %>%
  hc_chart(polar = TRUE, backgroundColor = "lightgrey") %>%
  hc_add_series(data = epl_drib_90_full_scaled,
                mapping = hcaes(x = variable, y = 1),
                type = "point",
                tooltip = list(pointFormat = "{point.variable}"),
                color = "lightgrey",
                animation = FALSE,
                showInLegend = FALSE) %>%  
  hc_add_series(data = epl_drib_90_full_scaled, 
                mapping = hcaes(x = variable, y = value.scaled), 
                type = "column",
                color = rgb(0,255,100, maxColorValue = 255),
                tooltip = list(pointFormat = "{point.variable}: {point.value}"),
                showInLegend = FALSE,
                pointWidth = 0.25,
                borderColor = "darkgrey",
                borderWidth = .2) %>%
  hc_xAxis(categories = epl_drib_90_full_scaled$variable) %>%
  hc_yAxis(visible = FALSE,
           max = 1,
           tickPixelInterval = 0.01) %>%
  hc_title(text = epl_drib_90_player$Name,
           align = "center") %>%
  hc_subtitle(text = epl_drib_90_player$Squad,
              align = "center")
```

```{r}
epl_drib_90_table <- epl_drib_90_full_scaled %>% select(variable, value, value.scaled) %>%
  rename(Stat = variable,
         Value = value,
         `Scaled Value` = value.scaled)
kable(epl_drib_90_table, digits = 3, title = "Dribbling per 90 Minutes")
```


```{r}
epl_goalkeeper <- read_csv("data/epl_goalkeeper.csv", skip = 1) %>% 
  select(-c(3, Matches)) %>%
  separate(Nation, into = c("irrel", "Nation"), sep = " ") %>%
  select(-c(irrel))

epl_goalkeeper_90 <- read_csv("data/epl_goalkeeper_90.csv", skip = 1) %>% 
  select(-c(Matches)) %>%
  separate(Nation, into = c("irrel", "Nation"), sep = " ") %>%
  select(-c(irrel))
```

```{r}
epl_goalkeeperadvanced <- read_csv("data/epl_goalkeeperadvanced.csv", skip = 1) %>% 
  select(-c(3, Matches)) %>%
  separate(Nation, into = c("irrel", "Nation"), sep = " ") %>%
  select(-c(irrel))
epl_goalkeeperadvanced

epl_goalkeeperadvanced_90 <- read_csv("data/epl_goalkeeperadvanced_90.csv", skip = 1) %>% 
  select(-c(Matches)) %>%
  separate(Nation, into = c("irrel", "Nation"), sep = " ") %>%
  select(-c(irrel))
```

```{r}
epl_gk_comb <- left_join(epl_goalkeeper, epl_goalkeeperadvanced) %>% 
  rename(`Save%` = `Save%...17`,
         `PK Save%` = `Save%...27`)
epl_gk_90_comb <- left_join(epl_goalkeeper_90, epl_goalkeeperadvanced_90)  %>% 
  rename(`Save%` = `Save%...16`,
         `PK Save%` = `Save%...26`)
```

```{r}
epl_gk_dist_main <- epl_gk_comb %>% 
  select(c(1:11, 34:43, 47, 49))

epl_gk_dist_main_max <- epl_gk_dist_main %>% 
  drop_na() %>%
  filter(`90s` >= 4) %>% 
  summarise_if(is.numeric, max)
epl_gk_dist_main_min <- epl_gk_dist_main %>% 
  drop_na() %>%
  filter(`90s` >= 4) %>%
  summarise_if(is.numeric, min)

epl_gk_dist_player <- epl_gk_dist_main %>% filter(Name == "Nick Pope")

epl_gk_dist_main_max_min <- bind_rows(epl_gk_dist_main_max, epl_gk_dist_main_min)

epl_gk_dist_full <-bind_rows(epl_gk_dist_main_max_min, epl_gk_dist_player) %>%
  select(-c(Age, Squad, Pos, Nation, Name, Rk, Born, `90s`, Starts, Min, MP))

epl_gk_dist_full_scaled <- epl_gk_dist_full %>% mutate(type = c("max", "min","player")) %>%
  pivot_longer(c(1:ncol(epl_gk_dist_full)), names_to = "variable", values_to = "value") %>%
  group_by(variable) %>%
  mutate(value.scaled = (value - min(value)) / (max(value) - min(value))) %>%
  filter(type == "player") %>%
  pivot_wider(names_from = variable, values_from = value.scaled) %>%
  pivot_longer(c(1:ncol(epl_gk_dist_full) + 2), names_to = "variable", values_to = "value.scaled") %>%
  filter(!is.na(value.scaled)) %>%
  arrange(match(variable, c("Pass Att",
                            "Pass AvgLen",
                            "Launched Cmp",
                            "Launched Att",
                            "Launched Cmp%",
                            "Launch%",
                            "GK Launch%",
                            "Gk AvgLen",
                            "GK Att",
                            "AvgDist",
                            "#OPA/90",
                            "#OPA",
                            "Throws")))

gk_dist_plot <- highchart() %>%
  hc_chart(polar = TRUE, backgroundColor = "lightgrey") %>%
  hc_add_series(data = epl_gk_dist_full_scaled,
                mapping = hcaes(x = variable, y = 1),
                type = "point",
                tooltip = list(pointFormat = "{point.variable}"),
                color = "lightgrey",
                animation = FALSE,
                showInLegend = FALSE) %>%  
  hc_add_series(data = epl_gk_dist_full_scaled, 
                mapping = hcaes(x = variable, y = value.scaled), 
                type = "column",
                color = rgb(0,255,100, maxColorValue = 255),
                tooltip = list(pointFormat = "{point.variable}: {point.value}"),
                showInLegend = FALSE,
                pointWidth = 0.25,
                borderColor = "darkgrey",
                borderWidth = .2) %>%
  hc_xAxis(categories = epl_gk_dist_full_scaled$variable) %>%
  hc_yAxis(visible = FALSE,
           max = 1,
           tickPixelInterval = 0.01) %>%
  hc_title(text = epl_gk_dist_player$Name,
           align = "center") %>%
  hc_subtitle(text = epl_gk_dist_player$Squad,
              align = "center")
```

```{r}
epl_gk_dist_table <- epl_gk_dist_full_scaled %>% select(variable, value, value.scaled) %>%
  rename(Stat = variable,
         Value = value,
         `Scaled Value` = value.scaled)
kable(epl_gk_dist_table, digits = 3, title = "Goalkeeping Distribution")
```


```{r}
epl_gk_dist_90_main <- epl_gk_90_comb %>% 
  select(c(1:11, 34:43, 47))

epl_gk_dist_90_main_max <- epl_gk_dist_90_main %>% 
  drop_na() %>%
  filter(`90s` >= 4) %>% 
  summarise_if(is.numeric, max)
epl_gk_dist_90_main_min <- epl_gk_dist_90_main %>% 
  drop_na() %>%
  filter(`90s` >= 4) %>%
  summarise_if(is.numeric, min)

epl_gk_dist_90_player <- epl_gk_dist_90_main %>% filter(Name == "Nick Pope")

epl_gk_dist_90_main_max_min <- bind_rows(epl_gk_dist_90_main_max, epl_gk_dist_90_main_min)

epl_gk_dist_90_full <-bind_rows(epl_gk_dist_90_main_max_min, epl_gk_dist_90_player) %>%
  select(-c(Age, Squad, Pos, Nation, Name, Rk, Born, `90s`, Starts, Min, MP))

epl_gk_dist_90_full_scaled <- epl_gk_dist_90_full %>% mutate(type = c("max", "min","player")) %>%
  pivot_longer(c(1:ncol(epl_gk_dist_90_full)), names_to = "variable", values_to = "value") %>%
  group_by(variable) %>%
  mutate(value.scaled = (value - min(value)) / (max(value) - min(value))) %>%
  filter(type == "player") %>%
  pivot_wider(names_from = variable, values_from = value.scaled) %>%
  pivot_longer(c(1:ncol(epl_gk_dist_90_full) + 2), names_to = "variable", values_to = "value.scaled") %>%
  filter(!is.na(value.scaled)) %>%
  arrange(match(variable, c("Pass Att",
                            "Pass AvgLen",
                            "Launched Cmp",
                            "Launched Att",
                            "Launched Cmp%",
                            "Launch%",
                            "GK Launch%",
                            "Gk AvgLen",
                            "GK Att",
                            "#OPA",
                            "Throws")))

gk_dist_90_plot <- highchart() %>%
  hc_chart(polar = TRUE, backgroundColor = "lightgrey") %>%
  hc_add_series(data = epl_gk_dist_90_full_scaled,
                mapping = hcaes(x = variable, y = 1),
                type = "point",
                tooltip = list(pointFormat = "{point.variable}"),
                color = "lightgrey",
                animation = FALSE,
                showInLegend = FALSE) %>%  
  hc_add_series(data = epl_gk_dist_90_full_scaled, 
                mapping = hcaes(x = variable, y = value.scaled), 
                type = "column",
                color = rgb(0,255,100, maxColorValue = 255),
                tooltip = list(pointFormat = "{point.variable}: {point.value}"),
                showInLegend = FALSE,
                pointWidth = 0.25,
                borderColor = "darkgrey",
                borderWidth = .2) %>%
  hc_xAxis(categories = epl_gk_dist_90_full_scaled$variable) %>%
  hc_yAxis(visible = FALSE,
           max = 1,
           tickPixelInterval = 0.01) %>%
  hc_title(text = epl_gk_dist_90_player$Name,
           align = "center") %>%
  hc_subtitle(text = epl_gk_dist_90_player$Squad,
              align = "center")
```

```{r}
epl_gk_dist_90_table <- epl_gk_dist_90_full_scaled %>% select(variable, value, value.scaled) %>%
  rename(Stat = variable,
         Value = value,
         `Scaled Value` = value.scaled)
kable(epl_gk_dist_90_table, digits = 3, title = "Goalkeeping Distribution per 90 Minutes")
```

```{r}
epl_gk_base_main <- epl_gk_comb %>% 
  select(c(1:12, 14:16, 20, 21, 30:32, 44:46, 47, 49))

epl_gk_base_main_max <- epl_gk_base_main %>% 
  drop_na() %>%
  filter(`90s` >= 4) %>% 
  summarise_if(is.numeric, max)
epl_gk_base_main_min <- epl_gk_base_main %>% 
  drop_na() %>%
  filter(`90s` >= 4) %>%
  summarise_if(is.numeric, min)

epl_gk_base_player <- epl_gk_base_main %>% filter(Name == "Ederson")

epl_gk_base_main_max_min <- bind_rows(epl_gk_base_main_max, epl_gk_base_main_min)

epl_gk_base_full <-bind_rows(epl_gk_base_main_max_min, epl_gk_base_player) %>%
  select(-c(Age, Squad, Pos, Nation, Name, Rk, Born, `90s`, Starts, Min))

epl_gk_base_full_scaled <- epl_gk_base_full %>% mutate(type = c("max", "min","player")) %>%
  pivot_longer(c(1:ncol(epl_gk_base_full)), names_to = "variable", values_to = "value") %>%
  group_by(variable) %>%
  mutate(value.scaled = (value - min(value)) / (max(value) - min(value))) %>%
  filter(type == "player") %>%
  pivot_wider(names_from = variable, values_from = value.scaled) %>%
  mutate(GA = 1 - GA) %>%
  pivot_longer(c(1:ncol(epl_gk_base_full) + 2), names_to = "variable", values_to = "value.scaled") %>%
  filter(!is.na(value.scaled)) %>%
  arrange(match(variable, c("GA",
                            "SoTA",
                            "Saves", 
                            "Save%",
                            "PSxG",
                            "PSxG/SoT",
                            "PSxG+/-",
                            "Opp Cross",
                            "Stp Cross",
                            "Stp% Cross",
                            "#OPA",
                            "#OPA/90",
                            "AvgDist",
                            "CS%",
                            "CS",
                            "MP")))
  

gk_base_plot <- highchart() %>%
  hc_chart(polar = TRUE, backgroundColor = "lightgrey") %>%
  hc_add_series(data = epl_gk_base_full_scaled,
                mapping = hcaes(x = variable, y = 1),
                type = "point",
                tooltip = list(pointFormat = "{point.variable}"),
                color = "lightgrey",
                animation = FALSE,
                showInLegend = FALSE) %>%  
  hc_add_series(data = epl_gk_base_full_scaled, 
                mapping = hcaes(x = variable, y = value.scaled), 
                type = "column",
                color = rgb(0,255,100, maxColorValue = 255),
                tooltip = list(pointFormat = "{point.variable}: {point.value}"),
                showInLegend = FALSE,
                pointWidth = 0.25,
                borderColor = "darkgrey",
                borderWidth = .2) %>%
  hc_xAxis(categories = epl_gk_base_full_scaled$variable) %>%
  hc_yAxis(visible = FALSE,
           max = 1,
           tickPixelInterval = 0.01) %>%
  hc_title(text = epl_gk_base_player$Name,
           align = "center") %>%
  hc_subtitle(text = epl_gk_base_player$Squad,
              align = "center")
```

```{r}
epl_gk_base_table <- epl_gk_base_full_scaled %>% select(variable, value, value.scaled) %>%
  rename(Stat = variable,
         Value = value,
         `Scaled Value` = value.scaled)
kable(epl_gk_base_table, digits = 3, title = "Goalkeeping")
```


```{r}
epl_gk_90_base_main <- epl_gk_90_comb %>% 
  select(c(1:12, 14:16, 20, 21, 30:32, 44:46, 47))

epl_gk_90_base_main_max <- epl_gk_90_base_main %>% 
  drop_na() %>%
  filter(`90s` >= 4) %>% 
  summarise_if(is.numeric, max)
epl_gk_90_base_main_min <- epl_gk_90_base_main %>% 
  drop_na() %>%
  filter(`90s` >= 4) %>%
  summarise_if(is.numeric, min)

epl_gk_90_base_player <- epl_gk_90_base_main %>% filter(Name == "Nick Pope")

epl_gk_90_base_main_max_min <- bind_rows(epl_gk_90_base_main_max, epl_gk_90_base_main_min)

epl_gk_90_base_full <-bind_rows(epl_gk_90_base_main_max_min, epl_gk_90_base_player) %>%
  select(-c(Age, Squad, Pos, Nation, Name, Rk, Born, `90s`, Starts, Min))

epl_gk_90_base_full_scaled <- epl_gk_90_base_full %>% mutate(type = c("max", "min","player")) %>%
  pivot_longer(c(1:ncol(epl_gk_90_base_full)), names_to = "variable", values_to = "value") %>%
  group_by(variable) %>%
  mutate(value.scaled = (value - min(value)) / (max(value) - min(value))) %>%
  filter(type == "player") %>%
  pivot_wider(names_from = variable, values_from = value.scaled) %>%
  mutate(GA = 1 - GA) %>%
  pivot_longer(c(1:ncol(epl_gk_90_base_full) + 2), names_to = "variable", values_to = "value.scaled") %>%
  filter(!is.na(value.scaled)) %>%
  arrange(match(variable, c("GA",
                            "SoTA",
                            "Saves", 
                            "Save%",
                            "PSxG",
                            "PSxG/SoT",
                            "PSxG+/-",
                            "Opp Cross",
                            "Stp Cross",
                            "Stp% Cross",
                            "#OPA",
                            "#OPA/90",
                            "CS%",
                            "CS",
                            "MP")))
  

gk_90_base_plot <- highchart() %>%
  hc_chart(polar = TRUE, backgroundColor = "lightgrey") %>%
  hc_add_series(data = epl_gk_90_base_full_scaled,
                mapping = hcaes(x = variable, y = 1),
                type = "point",
                tooltip = list(pointFormat = "{point.variable}"),
                color = "lightgrey",
                animation = FALSE,
                showInLegend = FALSE) %>%  
  hc_add_series(data = epl_gk_90_base_full_scaled, 
                mapping = hcaes(x = variable, y = value.scaled), 
                type = "column",
                color = rgb(0,255,100, maxColorValue = 255),
                tooltip = list(pointFormat = "{point.variable}: {point.value}"),
                showInLegend = FALSE,
                pointWidth = 0.25,
                borderColor = "darkgrey",
                borderWidth = .2) %>%
  hc_xAxis(categories = epl_gk_90_base_full_scaled$variable) %>%
  hc_yAxis(visible = FALSE,
           max = 1,
           tickPixelInterval = 0.01) %>%
  hc_title(text = epl_gk_90_base_player$Name,
           align = "center") %>%
  hc_subtitle(text = epl_gk_90_base_player$Squad,
              align = "center")
```

```{r}
epl_gk_90_base_table <- epl_gk_90_base_full_scaled %>% select(variable, value, value.scaled) %>%
  rename(Stat = variable,
         Value = value,
         `Scaled Value` = value.scaled)
kable(epl_gk_90_base_table, digits = 3, title = "Goalkeeping per 90 Minutes")
```

















  














```{r}
library(shiny)
library(shinyWidgets)

ui <- fluidPage(
  sidebarLayout(
    sidebarPanel(
     selectizeInput("playerchoice",
                     label = "Choose a Player",
                     choices = levels(factor(epl_standard$Name)))
    
  ),
  mainPanel(
    submitButton("Update", icon("refresh"), width = 1150),
    verbatimTextOutput("text"),
    prettyCheckbox("check90", "per 90 min", FALSE, inline = TRUE),
    prettyCheckbox("checkPOS", "position", FALSE, inline = TRUE),
    tabsetPanel(
      tabPanel("Shooting", 
               highchartOutput("shootPlot", height = "80vh"),
               tableOutput("shootTable")),
      tabPanel("Passing",
               highchartOutput("passPlot", height = "80vh"),
               tableOutput("passTable"))
    ))
  )
)

server <- function(input, output, session) {
  
  output$text <- renderText({
    paste("Filters:")
  })
  
  ##SHOOTING
  epl_shooting_max <- reactive({
    if (input$checkPOS == FALSE) {
      epl_shooting %>%
      drop_na() %>%
      filter(`90s` >= 4,
             Pos != "GK") %>% 
      summarise_if(is.numeric, max)
  }
    else {
      pos_max <- left_join(epl_shooting %>% drop_na(), epl_positions) %>%
        filter(`90s` >= 4,
               Pos != "GK") %>% 
        pivot_longer(cols = c(Pos1, Pos2, Pos3), names_to = "type", values_to = "position") 
      player_pos <- left_join(epl_standard, epl_positions) %>% 
        filter(Name == input$playerchoice) %>%
        pivot_longer(cols = c(Pos1, Pos2, Pos3), names_to = "type", values_to = "position") %>%
        filter(!is.na(position))
      semi_join(pos_max, player_pos, by = c("position" = "position")) %>%
      pivot_wider(names_from = "type", values_from = "position") %>%
      summarise_if(is.numeric, max)
    }
  })
  
  epl_shooting_min <- reactive({ 
    if (input$checkPOS == FALSE) {
      epl_shooting %>% 
      drop_na() %>%
      filter(`90s` >= 4,
             Pos != "GK") %>%
      summarise_if(is.numeric, min)
    }
    else {
      pos_min <- left_join(epl_shooting %>% drop_na(), epl_positions) %>%
        filter(`90s` >= 4,
               Pos != "GK") %>% 
        pivot_longer(cols = c(Pos1, Pos2, Pos3), names_to = "type", values_to = "position")
      player_pos <- left_join(epl_standard, epl_positions) %>% 
        filter(Name == input$playerchoice) %>%
        pivot_longer(cols = c(Pos1, Pos2, Pos3), names_to = "type", values_to = "position") %>%
        filter(!is.na(position))
      semi_join(pos_min, player_pos, by = c("position" = "position")) %>%
      pivot_wider(names_from = "type", values_from = "position") %>%
      summarise_if(is.numeric, min)
    }
    })
 
  epl_shooting_max_min <- reactive({
    bind_rows(epl_shooting_max(), epl_shooting_min())
    })
  epl_shoot_player <- reactive({
      epl_shooting %>% filter(Name == input$playerchoice)
    })
  epl_shoot_full <- reactive({
    bind_rows(epl_shooting_max_min(), epl_shoot_player()) %>%
      select(-c(Age, Squad, Pos, Nation, Name, Rk, Born, `90s`, FK, PKatt, PK))
    })
  epl_shoot_full_scaled <- reactive({ 
    epl_shoot_full() %>% 
    mutate(type = c("max", "min","player")) %>%
    pivot_longer(c(1:ncol(epl_shoot_full())), names_to = "variable", values_to = "value") %>%
    group_by(variable) %>%
    mutate(value.scaled = (value - min(value)) / (max(value) - min(value))) %>%
    filter(type == "player") %>%
    pivot_wider(names_from = variable, values_from = value.scaled) %>%
    mutate(`G-xG` = 1 - `G-xG`,
           `np:G-xG` = 1- `np:G-xG`) %>% 
    rename(Goals = Gls,
           Shots = Sh,
           `Shots on Target` = SoT,
           `Shots on Target%` = `SoT%`,
           `Goals/Shot` = `G/Sh`,
           `Goals/Shot on Target` = `G/SoT`,
           Distance = Dist,
           `Non Penalty: xGoals/Shot` = `npxG/Sh`,
           `Non Penalty: Goals - xGoals` = `np:G-xG`,
           `Goals - xGoals` = `G-xG`,
           `Non Penalty xGoals` = npxG,
           `xGoals` = xG) %>%
    pivot_longer(c(1:ncol(epl_shoot_full()) + 2), names_to = "variable", values_to = "value.scaled") %>%
    filter(!is.na(value.scaled)) %>%
    arrange(match(variable, c("Goals",
                              "Shots",
                              "Goals/Shot",
                              "Shots on Target",
                              "Shots on Target%",
                              "Goals/Shot on Target",
                              "Distance",
                              "Non Penalty: xGoals/Shot",
                              "Non Penalty: Goals - xGoals",
                              "Non Penalty xGoals",
                              "Goals - xGoals",
                              "xGoals")))
  })
  shooting_plot <- reactive({
  highchart() %>%
  hc_chart(polar = TRUE,
           gridWidth = 2,
           gridLineColor = "white",
           backgroundColor = rgb(115,194,251, maxColorValue = 255),
           style = list(fontSize = 24)
           ) %>%
  hc_add_theme(hc_theme_google()) %>%
  hc_add_series(data = epl_shoot_full_scaled(), 
                mapping = hcaes(x = variable, y = value.scaled), 
                type = "column",
                tooltip = list(headFormat = "{point.variable}", pointFormat = "{point.value}"),
                showInLegend = FALSE,
                pointWidth = 0.5,
                borderColor = "black",
                borderWidth = .15,
                color = "red"
                ) %>%
  hc_add_series(data = shooting_descr,
                mapping = hcaes(x = variable, y = 1),
                type = "point",
                tooltip = list(headerFormat = "", pointFormat = "{point.description}"),
                animation = FALSE,
                showInLegend = FALSE,
                gridLineColor = "white",
                color = rgb(115,194,251, maxColorValue = 255)
                ) %>%
  hc_xAxis(categories = epl_shoot_full_scaled()$variable) %>%
  hc_yAxis(visible = FALSE,
           max = 1,
           tickPixelInterval = 0.05
           ) %>%
  hc_subtitle(text = epl_shoot_player()$Name,
              align = "center",
              style = list(color = "black"),
              margin = 50) 
  })
  epl_shoot_table <- reactive({
    epl_shoot_full_scaled() %>% 
    select(variable, value, value.scaled) %>%
    rename(Stat = variable,
         Value = value,
         `Scaled Value` = value.scaled)
  })
  
  ## Shooting 90
   epl_shooting_90_max <- reactive({
    if (input$checkPOS == FALSE) {
      epl_shooting_90 %>%
      drop_na() %>%
      filter(`90s` >= 4,
             Pos != "GK") %>% 
      summarise_if(is.numeric, max)
  }
    else {
      pos_max <- left_join(epl_shooting_90 %>% drop_na(), epl_positions) %>%
        filter(`90s` >= 4,
               Pos != "GK") %>% 
        pivot_longer(cols = c(Pos1, Pos2, Pos3), names_to = "type", values_to = "position") 
      player_pos <- left_join(epl_standard, epl_positions) %>% 
        filter(Name == input$playerchoice) %>%
        pivot_longer(cols = c(Pos1, Pos2, Pos3), names_to = "type", values_to = "position") %>%
        filter(!is.na(position))
      semi_join(pos_max, player_pos, by = c("position" = "position")) %>%
      pivot_wider(names_from = "type", values_from = "position") %>%
      summarise_if(is.numeric, max)
    }
  })
  epl_shooting_90_min <- reactive({ 
    if (input$checkPOS == FALSE) {
      epl_shooting_90 %>% 
      drop_na() %>%
      filter(`90s` >= 4,
             Pos != "GK") %>%
      summarise_if(is.numeric, min)
    }
    else {
      pos_min <- left_join(epl_shooting_90 %>% drop_na(), epl_positions) %>%
        filter(`90s` >= 4,
               Pos != "GK") %>% 
        pivot_longer(cols = c(Pos1, Pos2, Pos3), names_to = "type", values_to = "position")
      player_pos <- left_join(epl_standard, epl_positions) %>% 
        filter(Name == input$playerchoice) %>%
        pivot_longer(cols = c(Pos1, Pos2, Pos3), names_to = "type", values_to = "position") %>%
        filter(!is.na(position))
      semi_join(pos_min, player_pos, by = c("position" = "position")) %>%
      pivot_wider(names_from = "type", values_from = "position") %>%
      summarise_if(is.numeric, min)
    }
    })
  epl_shooting_90_max_min <- reactive({
    bind_rows(epl_shooting_90_max(), epl_shooting_90_min())
    })
  epl_shoot_90_player <- reactive({
    epl_shooting_90 %>% filter(Name == input$playerchoice)
  })
  epl_shoot_90_full <- reactive({
    bind_rows(epl_shooting_90_max_min(), epl_shoot_90_player()) %>%
    select(-c(Age, Squad, Pos, Nation, Name, Rk, Born, `90s`, FK, PKatt, PK))
  })
  epl_shoot_90_full_scaled <- reactive({
  epl_shoot_90_full() %>% mutate(type = c("max", "min","player")) %>%
  pivot_longer(c(1:ncol(epl_shoot_90_full())), names_to = "variable", values_to = "value") %>%
  group_by(variable) %>%
  mutate(value.scaled = (value - min(value)) / (max(value) - min(value))) %>%
  filter(type == "player") %>%
  pivot_wider(names_from = variable, values_from = value.scaled) %>%
  mutate(`G-xG` = 1 - `G-xG`,
         `np:G-xG` = 1- `np:G-xG`) %>%
  rename(Goals = Gls,
         Shots = Sh,
         `Shots on Target` = SoT,
         `Shots on Target%` = `SoT%`,
         `Goals/Shot` = `G/Sh`,
         `Goals/Shot on Target` = `G/SoT`,
         Distance = Dist,
         `Non Penalty: xGoals/Shot` = `npxG/Sh`,
         `Non Penalty: Goals - xGoals` = `np:G-xG`,
         `Goals - xGoals` = `G-xG`,
         `Non Penalty xGoals` = npxG,
         `xGoals` = xG) %>%
  pivot_longer(c(1:ncol(epl_shoot_full()) + 2), names_to = "variable", values_to = "value.scaled") %>%
  filter(!is.na(value.scaled)) %>%
  arrange(match(variable, c("Goals",
                            "Shots",
                            "Goals/Shot",
                            "Shots on Target",
                            "Shots on Target%",
                            "Goals/Shot on Target",
                            "Distance",
                            "Non Penalty: xGoals/Shot",
                            "Non Penalty: Goals - xGoals",
                            "Non Penalty xGoals",
                            "Goals - xGoals",
                            "xGoals"))) 
  })
  shooting_90_plot <- reactive({
  highchart() %>%
  hc_chart(polar = TRUE, 
           backgroundColor = rgb(115,194,251, maxColorValue = 255),
           gridWidth = 2,
           gridLineColor = "white") %>%
  hc_add_theme(hc_theme_google()) %>%
  hc_add_series(data = shooting_descr,
                mapping = hcaes(x = variable, y = 1),
                type = "point",
                color = rgb(115,194,251, maxColorValue = 255),
                tooltip = list(headerFormat = "", pointFormat = "{point.description}"),
                animation = FALSE,
                showInLegend = FALSE) %>%   
  hc_add_series(data = epl_shoot_90_full_scaled(), 
                mapping = hcaes(x = variable, y = value.scaled), 
                type = "column",
                color = "red",
                tooltip = list(headFormat = "{point.variable}", pointFormat = "{point.value}"),
                showInLegend = FALSE,
                pointWidth = 0.5,
                borderColor = "black",
                borderWidth = .15) %>%
  hc_xAxis(categories = epl_shoot_full_scaled()$variable) %>%
  hc_yAxis(visible = FALSE,
           max = 1,
           tickPixelInterval = 0.01) %>%
  hc_subtitle(text = epl_shoot_90_player()$Name,
              stle = list(color = "black"),
              margin = 50,
              align = "center")
  })
  
  epl_shoot_90_table <- reactive({
    epl_shoot_90_full_scaled() %>% select(variable, value, value.scaled) %>%
    rename(Stat = variable,
         Value = value,
         `Scaled Value` = value.scaled)
  })
    
  output$shootPlot <- renderHighchart({
    if (input$check90 == FALSE) {
     shooting_plot()
    } 
    else {shooting_90_plot()}
  })
  output$shootTable <- renderTable({
    if (input$check90 == FALSE) {
      epl_shoot_table()
    }
    else {epl_shoot_90_table()}
  })
  
  
  ## PASSING
  epl_passing_max <- reactive({
    if (input$checkPOS == FALSE) {
      epl_passing_main%>%
      drop_na() %>%
      filter(`90s` >= 4,
             Pos != "GK") %>% 
      summarise_if(is.numeric, max)
  }
    else {
      pos_max <- left_join(epl_passing_main %>% drop_na(), epl_positions) %>%
        filter(`90s` >= 4,
               Pos != "GK") %>% 
        pivot_longer(cols = c(Pos1, Pos2, Pos3), names_to = "type", values_to = "position") 
      player_pos <- left_join(epl_standard, epl_positions) %>% 
        filter(Name == input$playerchoice) %>%
        pivot_longer(cols = c(Pos1, Pos2, Pos3), names_to = "type", values_to = "position") %>%
        filter(!is.na(position))
      semi_join(pos_max, player_pos, by = c("position" = "position")) %>%
      pivot_wider(names_from = "type", values_from = "position") %>%
      summarise_if(is.numeric, max)
    }
  })
  
  epl_passing_min <- reactive({ 
    if (input$checkPOS == FALSE) {
      epl_passing_main %>% 
      drop_na() %>%
      filter(`90s` >= 4,
             Pos != "GK") %>%
      summarise_if(is.numeric, min)
    }
    else {
      pos_min <- left_join(epl_passing_main %>% drop_na(), epl_positions) %>%
        filter(`90s` >= 4,
               Pos != "GK") %>% 
        pivot_longer(cols = c(Pos1, Pos2, Pos3), names_to = "type", values_to = "position")
      player_pos <- left_join(epl_standard, epl_positions) %>% 
        filter(Name == input$playerchoice) %>%
        pivot_longer(cols = c(Pos1, Pos2, Pos3), names_to = "type", values_to = "position") %>%
        filter(!is.na(position))
      semi_join(pos_min, player_pos, by = c("position" = "position")) %>%
      pivot_wider(names_from = "type", values_from = "position") %>%
      summarise_if(is.numeric, min)
    }
    })
 
  epl_passing_main_max_min <- reactive({
    bind_rows(epl_passing_max(), epl_passing_min())
    })
  epl_pass_player <- reactive({
    epl_passing_main %>% filter(Name == input$playerchoice)
  })
  epl_pass_full <- reactive({
    bind_rows(epl_passing_main_max_min(), epl_pass_player()) %>%
    select(-c(Age, Squad, Pos, Nation, Name, Rk, Born, `90s`))
  })
  epl_pass_full_scaled <- reactive({
    epl_pass_full() %>% mutate(type = c("max", "min","player")) %>%
    pivot_longer(c(1:ncol(epl_pass_full())), names_to = "variable", values_to = "value") %>%
    group_by(variable) %>%
    mutate(value.scaled = (value - min(value)) / (max(value) - min(value))) %>%
    filter(type == "player") %>%
    pivot_wider(names_from = variable, values_from = value.scaled) %>%
    rename(Completions = `Cmp Total`,
           Attempts = `Att Total`,
           `Completion %` = `Cmp% Total`,
           `Short Completions` = `Cmp Short`,
           `Short Completion %` = `Cmp% Short`,
           `Medium Completions` = `Cmp Medium`, 
           `Medium Completion %` = `Cmp% Medium`,
           `Long Completions` = `Cmp Long`,
           `Long Completion %` = `Cmp% Long`,
           `Progressive Completions` = Prog,
           Switches = Sw,
           `Pressure` = Press,
           `Through Balls` = TB,
           `Completions into Final 3rd` = `1/3`,
           `Completions into Penalty Area` = PPA,
           Crosses = Crs,
           `Key Passes` = KP,
           `Shot Creating Passes` = SCA_passes,
           `Goal Creating Passes` = GCA_passes,
           xAssists = xA,
           Assists = Ast) %>%
    pivot_longer(c(3:23), names_to = "variable", values_to = "value.scaled") %>%
    filter(!is.na(value.scaled)) %>%
    arrange(match(variable, c("Completions", 
                              "Attempts",
                              "Completion %",
                              "Short Completions",
                              "Short Completion %",
                              "Medium Completions",
                              "Medium Completion %",
                              "Long Completions",
                              "Long Completion %",
                              "Progressive Completions",
                              "Switches",
                              "Pressure",
                              "Through Balls",
                              "Completions into Final 3rd",
                              "Completions into Penalty Area",
                              "Crosses",
                              "Key Passes",
                              "Shot Creating Passes",
                              "Goal Creating Passes",
                              "xAssists",
                              "Assists")))
  })
  passing_plot <- reactive({
    highchart() %>%
    hc_chart(polar = TRUE,
             gridLineColor = "white",
             backgroundColor = rgb(115,194,251, maxColorValue = 255)) %>%
    hc_add_theme(hc_theme_google()) %>%
    hc_add_series(data = passing_descr,
                mapping = hcaes(x = variable, y = 1),
                type = "point",
                tooltip = list(headerFormat = "",pointFormat = "{point.description}"),
                animation = FALSE,
                showInLegend = FALSE,
                color = rgb(115,194,251, maxColorValue = 255)) %>%  
    hc_add_series(data = epl_pass_full_scaled(), 
                  mapping = hcaes(x = variable, y = value.scaled), 
                  type = "column",
                  tooltip = list(headFormat = "{point.variable}", pointFormat = "{point.value}"),
                  showInLegend = FALSE,
                  pointWidth = 0.25,
                  borderColor = "black",
                  borderWidth = .15,
                  color = "red") %>%
    hc_xAxis(categories = epl_pass_full_scaled()$variable) %>%
    hc_yAxis(visible = FALSE,
             max = 1,
             tickPixelInterval = 0.05) %>%
    hc_subtitle(text = epl_pass_player()$Name,
                align = "center",
                style = list(color = "black")) 
  })
  epl_pass_table <- reactive({
    epl_pass_full_scaled() %>% select(variable, value, value.scaled) %>%
    rename(Stat = variable,
           Value = value,
           `Scaled Value` = value.scaled)
  })
  
  ## Passing 90
   epl_passing_90_max <- reactive({
    if (input$checkPOS == FALSE) {
      epl_passing_90_main %>%
      drop_na() %>%
      filter(`90s` >= 4,
             Pos != "GK") %>% 
      summarise_if(is.numeric, max)
  }
    else {
      pos_max <- left_join(epl_passing_90_main %>% drop_na(), epl_positions) %>%
        filter(`90s` >= 4,
               Pos != "GK") %>% 
        pivot_longer(cols = c(Pos1, Pos2, Pos3), names_to = "type", values_to = "position") 
      player_pos <- left_join(epl_standard, epl_positions) %>% 
        filter(Name == input$playerchoice) %>%
        pivot_longer(cols = c(Pos1, Pos2, Pos3), names_to = "type", values_to = "position") %>%
        filter(!is.na(position))
      semi_join(pos_max, player_pos, by = c("position" = "position")) %>%
      pivot_wider(names_from = "type", values_from = "position") %>%
      summarise_if(is.numeric, max)
    }
  })
  epl_passing_90_min <- reactive({ 
    if (input$checkPOS == FALSE) {
      epl_passing_90_main %>% 
      drop_na() %>%
      filter(`90s` >= 4,
             Pos != "GK") %>%
      summarise_if(is.numeric, min)
    }
    else {
      pos_min <- left_join(epl_passing_90_main %>% drop_na(), epl_positions) %>%
        filter(`90s` >= 4,
               Pos != "GK") %>% 
        pivot_longer(cols = c(Pos1, Pos2, Pos3), names_to = "type", values_to = "position")
      player_pos <- left_join(epl_standard, epl_positions) %>% 
        filter(Name == input$playerchoice) %>%
        pivot_longer(cols = c(Pos1, Pos2, Pos3), names_to = "type", values_to = "position") %>%
        filter(!is.na(position))
      semi_join(pos_min, player_pos, by = c("position" = "position")) %>%
      pivot_wider(names_from = "type", values_from = "position") %>%
      summarise_if(is.numeric, min)
    }
    })
  epl_passing_90_main_max_min <- reactive({
    bind_rows(epl_passing_90_max(), epl_passing_90_min())
    })
  epl_pass_90_player <- reactive({ 
    epl_passing_90_main %>% filter(Name == input$playerchoice)
  })
  epl_pass_90_full <- reactive({
    bind_rows(epl_passing_90_main_max_min(), epl_pass_90_player()) %>%
    select(-c(Age, Squad, Pos, Nation, Name, Rk, Born, `90s`))
  })
  epl_pass_90_full_scaled <- reactive({
    epl_pass_90_full() %>% mutate(type = c("max", "min","player")) %>%
    pivot_longer(c(1:ncol(epl_pass_90_full())), names_to = "variable", values_to = "value") %>%
    group_by(variable) %>%
    mutate(value.scaled = (value - min(value)) / (max(value) - min(value))) %>%
    filter(type == "player") %>%
    pivot_wider(names_from = variable, values_from = value.scaled) %>%
    rename(Completions = `Cmp Total`,
           Attempts = `Att Total`,
           `Completion %` = `Cmp% Total`,
           `Short Completions` = `Cmp Short`,
           `Short Completion %` = `Cmp% Short`,
           `Medium Completions` = `Cmp Medium`, 
           `Medium Completion %` = `Cmp% Medium`,
           `Long Completions` = `Cmp Long`,
           `Long Completion %` = `Cmp% Long`,
           `Progressive Completions` = Prog,
           Switches = Sw,
           `Pressure` = Press,
           `Through Balls` = TB,
           `Completions into Final 3rd` = `1/3`,
           `Completions into Penalty Area` = PPA,
           Crosses = Crs,
           `Key Passes` = KP,
           `Shot Creating Passes` = SCA_passes,
           `Goal Creating Passes` = GCA_passes,
           xAssists = xA,
           Assists = Ast) %>%
    pivot_longer(c(3:23), names_to = "variable", values_to = "value.scaled") %>%
    filter(!is.na(value.scaled)) %>%
    arrange(match(variable, c("Completions", 
                              "Attempts",
                              "Completion %",
                              "Short Completions",
                              "Short Completion %",
                              "Medium Completions",
                              "Medium Completion %",
                              "Long Completions",
                              "Long Completion %",
                              "Progressive Completions",
                              "Switches",
                              "Pressure",
                              "Through Balls",
                              "Completions into Final 3rd",
                              "Completions into Penalty Area",
                              "Crosses",
                              "Key Passes",
                              "Shot Creating Passes",
                              "Goal Creating Passes",
                              "xAssists",
                              "Assists")))
  })
  passing_90_plot <- reactive({
    highchart() %>%
    hc_chart(polar = TRUE, 
             backgroundColor = rgb(115,194,251, maxColorValue = 255),
             gridWidth = 2,
             gridLineColor = "white") %>%
    hc_add_theme(hc_theme_google()) %>%
    hc_add_series(data = passing_descr,
                  mapping = hcaes(x = variable, y = 1),
                  type = "point",
                  tooltip = list(headerFormat = "", pointFormat = "{point.description}"),
                  color = rgb(115,194,251, maxColorValue = 255),
                  animation = FALSE,
                  showInLegend = FALSE,
                  gridLineColor = "white") %>%  
    hc_add_series(data = epl_pass_90_full_scaled(), 
                  mapping = hcaes(x = variable, y = value.scaled), 
                  type = "column",
                  color = "red",
                  tooltip = list(headFormat = "{point.variable}", pointFormat = "{point.value}"),
                  showInLegend = FALSE,
                  pointWidth = 0.25,
                  borderColor = "black",
                  borderWidth = .15) %>%
    hc_xAxis(categories = epl_pass_full_scaled()$variable) %>%
    hc_yAxis(visible = FALSE,
             max = 1,
             tickPixelInterval = 0.01) %>%
    hc_subtitle(text = epl_pass_90_player()$Name,
                align = "center")
  })
  epl_pass_90_table <- reactive({
    epl_pass_90_full_scaled() %>% 
      select(variable, value, value.scaled) %>%
    rename(Stat = variable,
         Value = value,
         `Scaled Value` = value.scaled)
  })
  
  output$passPlot <- renderHighchart({
    if (input$check90 == FALSE) {
      passing_plot()
    }
    else {passing_90_plot()}
  })
  output$passTable <- renderTable({
   if (input$check90 == FALSE) {  
    epl_pass_table()
   }
  else {epl_pass_90_table()}
  })
  
}

shinyApp(ui, server)
```





```{r}
pos_min <- left_join(epl_shooting %>% drop_na(), epl_positions) %>%
        filter(`90s` >= 4,
               Pos != "GK") %>% 
        pivot_longer(cols = c(Pos1, Pos2, Pos3), names_to = "type", values_to = "position")
      player_pos <- left_join(epl_standard, epl_positions) %>% 
        filter(Name == "Cristiano Ronaldo") %>%
        pivot_longer(cols = c(Pos1, Pos2, Pos3), names_to = "type", values_to = "position") %>%
        filter(!is.na(position))
      semi_join(pos_min, player_pos, by = c("position" = "position")) %>%
      pivot_wider(names_from = "type", values_from = "position") %>%
      summarise_if(is.numeric, min)
      
pos_max <- left_join(epl_shooting %>% drop_na(), epl_positions) %>%
        filter(`90s` >= 4,
               Pos != "GK") %>% 
        pivot_longer(cols = c(Pos1, Pos2, Pos3), names_to = "type", values_to = "position")
      player_pos <- left_join(epl_standard, epl_positions) %>% 
        filter(Name == "Cristiano Ronaldo") %>%
        pivot_longer(cols = c(Pos1, Pos2, Pos3), names_to = "type", values_to = "position") %>%
        filter(!is.na(position))
      semi_join(pos_max, player_pos, by = c("position" = "position")) %>%
      pivot_wider(names_from = "type", values_from = "position") %>%
      summarise_if(is.numeric, max)
```

  




