---
title: "Written Despription"
author: "Shane Hauck"
date: '2022-05-11'
output: html_document
---

  The purpose of this project is to give the users of the app the ability to visualize the deeper player statistics of English Premier League football in a way that is accurate and comparable. The use of this app is not necessarily intended for people who have a lack of knowledge of football as to make conclusions about the data shown the user should have a pre-existing idea of both the player’s style of play and their team’s style of play. The data compiled for this project was from https://fbref.com/en/comps/9/Premier-League-Stats as well as a dataset from https://www.kaggle.com/datasets/stefanoleone992/fifa-22-complete-player-dataset . There were 20 different datasets taken from fbref that featured the basis for all stats shown in the radar charts and stat tables. Many of these datasets contained deeper statistics in regard to the overarching theme of that section of data. These different sections were used in accordance with one another to split the categorization of data into the 5 different main categories: Shooting, Passing, Dribbling, Defending, and Possession.  The FIFA 22 player dataset was used more for the information of players, and it allowed for grouping players into the more accurate positions compared to the fbref datasets. 
	
	When creating the radar charts, one of the most important factors that had to be kept in mind was the ordering of the variables as the shape that the charts will present are dependent on it. The variables that are next to each other need to be closely related in a way that is natural and logical. Although I feel that I have ordered the categories in the best way possible to represent the skill of players most accurately, because of the preciseness of some of the data (for example the data that is positional for the location on the pitch) the shape of the radar chart is now more dependent on the type of player that is being featured. Some players will show lack of a stat just because of the position they play. For example, Strikers will have a very low number of touches in their team’s defensive penalty area, all because that is where they never are. Does that make them a worser player? No of course not, that’s just not their job. That is why I feel that to fully understand what these charts are showing you is the need for prior knowledge of players and teams. Yes, the size of the shape is important but just because they’re lacking stats in one or two variables as a result of an outside factor does not say they are a worse player than the next guy. All this is showing is what type of player each player is in regard to the system that each team plays. When looking at the charts you need to take in account how a player plays and understand that why they lack a certain statistic is as a result of their style of play which likely has a correlation with an enhancement in other related statistics. 
	
	In the future I hope to expand on the strides I have made with this project over this semester. First things first I would like to fix a couple of the subtle errors that are in the presentation (for example players that have played for multiple teams are unrepresented). I would also like to fix the overall graph tab into something that is more reactive like the other deeper statistic tabs.  I want to expand this app to being more than just players and somehow include the teams so users could make comparisons using both. I also would like to add a couple things to the app that would make it a little more user friendly. I plan on using this app to do my own research and write my own journal articles featuring player analysis as well as deeper football analysis pieces.